"""Neutral Border admission and evidence-provenance contracts."""
from .authority_adapter import (
    AuthorityAdapterError,
    IdentityAuthorityAdapter,
    ProfileReport,
    analyze_profile,
)
from .admission import (
    AdmissionError,
    AdmissionResult,
    BorderAdmissionController,
    document_digest,
    stamp_bindings,
    verify_gate_context,
)
from .jcs import CanonicalizationError, canonicalize
from .dsse import (
    admission_statement,
    hmac_sha256_signer,
    hmac_sha256_verifier,
    pre_auth_encoding,
    sign_envelope,
    verify_envelope,
)
from .stamper import stamp_admission
from .reference_authorities import (
    CapabilityGrantAuthorityProvider,
    SignedTokenAuthorityProvider,
)
from .openid_aiim import (OAuthAccessAuthorityProvider, protected_resource_metadata,
                          validate_cimd_document, www_authenticate)
from .openid_gateway import (HttpResponse, OpenIDGatewayServer, OAuthMcpClient,
                             PendingAuthorization, UrllibTransport,
                             authorization_server_metadata_urls)
from .openid_evidence import InteropEvidenceLog
from .subject_link import (
    SubjectLinkError,
    SubjectLinkEvidence,
    SubjectRequirement,
    SubjectRequirementResult,
    evaluate_subject_requirement,
    normalize_subject_link,
)
from .mandate_adapter import (
    MANDATE_PREDICATE_TYPE,
    MandateAdapterContext,
    MandateAdapterError,
    MandateAuthorityAdapter,
    mandate_statement,
    stamp_mandate_receipt,
    verify_mandate_gate_context,
)
from .intent_continuity import (
    INTENT_CONTINUITY_PREDICATE_TYPE,
    IntentContinuityError,
    intent_continuity_statement,
    prove_intent_continuity,
    stamp_intent_continuity,
    verify_intent_continuity_stamp,
)
from .protocol_continuity import (
    EXTENSION as INTENT_CONTINUITY_EXTENSION,
    ContinuityTrustProvider,
    a2a_delegation,
    final_effect_from_http_x402,
    mcp_delegation,
    prove_protocol_continuity,
    prove_protocol_continuity_with_provider,
)

__all__ = [
    "AuthorityAdapterError",
    "IdentityAuthorityAdapter",
    "ProfileReport",
    "analyze_profile",
    "AdmissionError",
    "AdmissionResult",
    "BorderAdmissionController",
    "document_digest",
    "stamp_bindings",
    "verify_gate_context",
    "CanonicalizationError",
    "canonicalize",
    "admission_statement",
    "hmac_sha256_signer",
    "hmac_sha256_verifier",
    "pre_auth_encoding",
    "sign_envelope",
    "verify_envelope",
    "stamp_admission",
    "CapabilityGrantAuthorityProvider",
    "SignedTokenAuthorityProvider",
    "OAuthAccessAuthorityProvider",
    "protected_resource_metadata",
    "validate_cimd_document",
    "www_authenticate",
    "HttpResponse",
    "OpenIDGatewayServer",
    "OAuthMcpClient",
    "PendingAuthorization",
    "authorization_server_metadata_urls",
    "UrllibTransport",
    "InteropEvidenceLog",
    "SubjectLinkError",
    "SubjectLinkEvidence",
    "SubjectRequirement",
    "SubjectRequirementResult",
    "evaluate_subject_requirement",
    "normalize_subject_link",
    "MANDATE_PREDICATE_TYPE",
    "MandateAdapterContext",
    "MandateAdapterError",
    "MandateAuthorityAdapter",
    "mandate_statement",
    "stamp_mandate_receipt",
    "verify_mandate_gate_context",
    "IntentContinuityError",
    "INTENT_CONTINUITY_PREDICATE_TYPE",
    "intent_continuity_statement",
    "prove_intent_continuity",
    "stamp_intent_continuity",
    "verify_intent_continuity_stamp",
    "INTENT_CONTINUITY_EXTENSION",
    "ContinuityTrustProvider",
    "a2a_delegation",
    "mcp_delegation",
    "final_effect_from_http_x402",
    "prove_protocol_continuity",
    "prove_protocol_continuity_with_provider",
]
